#!/bin/sh

set -e

git am --quit || true

git checkout build
git reset --hard v22.03

# Introduce support for RISC-V architecture
# https://inbox.dpdk.org/dev/20220505173003.3242618-1-kda@semihalf.com/
git am ../patches/0001-lpm-add-a-scalar-version-of-lookupx4-function.patch
git am ../patches/0001-examples-l3fwd-fix-scalar-LPM-compilation.patch
git am ../patches/0001-eal-add-initial-support-for-RISC-V-architecture.patch
git am ../patches/0001-net-ixgbe-enable-vector-stubs-for-RISC-V.patch
git am ../patches/0001-net-memif-set-memfd-syscall-ID-on-RISC-V.patch
git am ../patches/0001-net-tap-set-BPF-syscall-ID-for-RISC-V.patch
git am ../patches/0001-examples-l3fwd-enable-RISC-V-operation.patch
git am ../patches/0001-test-cpuflags-add-test-for-RISC-V-cpu-flag.patch
git am ../patches/0001-test-ring-disable-problematic-tests-for-RISC-V.patch
git am ../patches/0001-devtools-add-RISC-V-to-test-meson-builds.sh.patch
git am ../patches/0001-test-hash-report-non-HTM-numbers-for-single-r-w.patch

git am ../patches/0001-drivers-define-OPENSSL_API_COMPAT.patch
